version: '3.9'

services:
  users-api:
    build:
      context: ../TechChallengeFIAP.UsersAPI
      dockerfile: Dockerfile
    container_name: users-api
    ports:
      - "5000:80"
    environment:
      # Simulando ConfigMap (variáveis não sensíveis)
      SOME_SETTING: "valor"
      # Simulando Secret (variáveis sensíveis)
      DATABASE_CONNECTION: "Server=db;Database=users;User Id=sa;Password=1234;"
      RABBITMQ_PASSWORD: "secret"
    depends_on:
      - rabbitmq

  catalog-api:
    build:
      context: ../TechChallengeFIAP.Catalog.API
      dockerfile: Dockerfile
    container_name: catalog-api
    ports:
      - "5001:80"
    environment:
      SOME_SETTING: "valor"
      DATABASE_CONNECTION: "Server=db;Database=catalog;User Id=sa;Password=1234;"
      RABBITMQ_PASSWORD: "secret"
    depends_on:
      - rabbitmq

  payments-worker:
    build:
      context: ../TechChallengeFIAP.Payments.Worker
      dockerfile: Dockerfile
    container_name: payments-worker
    environment:
      SOME_SETTING: "valor"
      DATABASE_CONNECTION: "Server=db;Database=payments;User Id=sa;Password=1234;"
      RABBITMQ_PASSWORD: "secret"
    depends_on:
      - rabbitmq

  notifications-worker:
    build:
      context: ../TechChallengeFIAP.Notifications.Worker
      dockerfile: Dockerfile
    container_name: notifications-worker
    environment:
      SOME_SETTING: "valor"
      DATABASE_CONNECTION: "Server=db;Database=notifications;User Id=sa;Password=1234;"
      RABBITMQ_PASSWORD: "secret"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret