services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret

  users-api:
    build:
      context: ../
      dockerfile: TechChallengeFIAP.UsersAPI/Dockerfile
    container_name: users-api
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_CONNECTION: amqp://user:secret@rabbitmq:5672
    depends_on:
      - rabbitmq

  catalog-api:
    build:
      context: ../
      dockerfile: TechChallengeFIAP.Catalog.API/Dockerfile
    container_name: catalog-api
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_CONNECTION: amqp://user:secret@rabbitmq:5672
    depends_on:
      - rabbitmq

  payments-worker:
    build:
      context: ../
      dockerfile: TechChallengeFIAP.Payments.Worker/Dockerfile
    container_name: payments-worker
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_CONNECTION: amqp://user:secret@rabbitmq:5672
    depends_on:
      - rabbitmq

  notifications-worker:
    build:
      context: ../
      dockerfile: TechChallengeFIAP.Notifications.Worker/Dockerfile
    container_name: notifications-worker
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_CONNECTION: amqp://user:secret@rabbitmq:5672
    depends_on:
      - rabbitmq